

INSERT INTO BOOK (TITLE) VALUES ('KNIGA1');

INSERT INTO AUTHOR (LAST_NAME) VALUES ('AUTHOR1');

INSERT INTO GENRE (GENRE) VALUES ('GENRE1');

INSERT INTO BOOK_AUTHOR (BOOK_ID,AUTHOR_ID) VALUES (1,1);

INSERT INTO BOOK_GENRE (BOOK_ID, GENRE_ID) VALUES (1,1);
