spring:
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
logging:
  level: debug
